// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter_Api.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20191101212102_pictures")]
    partial class pictures
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("AnimalShelter.Models.ShelterList", b =>
                {
                    b.Property<int>("ShelterListId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("KennelNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PhotoPath")
                        .IsRequired();

                    b.HasKey("ShelterListId");

                    b.ToTable("ShelterList");

                    b.HasData(
                        new
                        {
                            ShelterListId = 1,
                            Age = 2,
                            AnimalType = "Alpaca",
                            Breed = "Suri",
                            Description = "Carla is sassy and love big Open spaces. She is the leader of the group.",
                            Gender = "Female",
                            KennelNumber = "7E",
                            Name = "Carla",
                            PhotoPath = "wwwroot/uploads/Carla.jpg"
                        },
                        new
                        {
                            ShelterListId = 2,
                            Age = 8,
                            AnimalType = "Caiman",
                            Breed = "Cuvier's dwarf",
                            Description = "He may be small, but Ruddy is feisty. Watch your fingers!",
                            Gender = "Male",
                            KennelNumber = "1R",
                            Name = "Ruddy",
                            PhotoPath = "wwwroot/uploads/Carla.jpg"
                        },
                        new
                        {
                            ShelterListId = 3,
                            Age = 1,
                            AnimalType = "Frog",
                            Breed = "Tomato",
                            Description = "He's a  frog. He does froggy things. He loves the hand taxi. Will do a heckin' monch before trusting hand taxi.",
                            Gender = "Male",
                            KennelNumber = "5A",
                            Name = "Sticky",
                            PhotoPath = "wwwroot/uploads/Carla.jpg"
                        },
                        new
                        {
                            ShelterListId = 4,
                            Age = 1,
                            AnimalType = "Dog",
                            Breed = "Chinese Crested",
                            Description = "Toad is a fashionista. If she isn't wearing a cute outfit, she shakes uncontrollably from her naked rage.",
                            Gender = "Female",
                            KennelNumber = "3D",
                            Name = "Toad",
                            PhotoPath = "wwwroot/uploads/Carla.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
