// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OregonHerp.Models;

namespace OregonHerp_Api.Migrations
{
    [DbContext(typeof(OregonHerpContext))]
    [Migration("20200120095810_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("OregonHerp.Models.HerpList", b =>
                {
                    b.Property<int>("HerpListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breeding");

                    b.Property<string>("Classification");

                    b.Property<string>("CommonName");

                    b.Property<string>("ConservationStatus");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Diet");

                    b.Property<string>("Diseases");

                    b.Property<string>("Habitat")
                        .IsRequired();

                    b.Property<bool>("InvasiveStatus");

                    b.Property<string>("Lifespan");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Predators");

                    b.Property<string>("ScientificName")
                        .IsRequired();

                    b.Property<string>("Size");

                    b.HasKey("HerpListId");

                    b.ToTable("HerpList");

                    b.HasData(
                        new
                        {
                            HerpListId = 1,
                            Breeding = "Tiger salamaders are loyal to where they were born and will travel long distances to return. They have only a 50% chance of breeding more than once in their lifetime and only breed in the later winter and early spring months. After about 48 hours after insemination, the female will lay her eggs in the breeding pool, attaching them to secure places to ensure their safety. Their larvae are entirely aquatic with external gills and a prominent caudal fin, similar to Axolotls.In certain cases, where the weather is warmer, they may not metamorphose until they are adult size. They also have been known to never metamorphose and stay in their larva stage their entire lives and reach sexual maturity while in their larva form.",
                            Classification = "Amphibian",
                            CommonName = "Tiger Salamander",
                            ConservationStatus = "Least     Concern",
                            Description = "Brown or black bodies with either brownish-yellow or greenish yellow spots on their heads, bodies, and tails.",
                            Diet = "Insects, earthworms, grubs, small snails, slugs, minnows, other amphibians (in rare cases, other tiger salamanders), crustacians (while in their larva form).",
                            Diseases = "Although immune, tiger salamaders transmit amphibian chytrid fungus which causes Chytridiomycosis which affects amphibians worldwide. They also carry ranaviruses which infects reptiles, amphibians, and fish, and has been linked to high mortality in tiger salamander larvae when there's reoccuring ranavirus infections.",
                            Habitat = "Wetlands, rivers and streams. They are mostly terrestrial, only returning to the water to breed.",
                            InvasiveStatus = false,
                            Lifespan = "12-15 years",
                            PhotoPath = "../wwwroot/uploads/tigerSalamander.jpg",
                            Predators = "Racoons, Coatis, river turtles, garter snakes, small mammals, birds, fish.",
                            ScientificName = "Ambystoma tigrinum",
                            Size = "15-20 cm"
                        },
                        new
                        {
                            HerpListId = 2,
                            Breeding = "Northwestern Salamanders breed in low-elevation sites during June to late August after migrating to breeding sites between January and April. They become sexually mature at 1-2 years of age. Their breeding occures in permanent and semi-permanent lakes, ponds, wetlands, and slow flowing rivers and streams, even if ice is still present. Males will often arrive before females, and the breading season lasts aproximately 1-7 weeks, which is dependant on the temperature increase rate of the water.Females lay about 30-270 eggs, if they are fully metamorphosed, in masses about the size of an orange, atatching them to secure locations underwater. If the female is not fully metamorphosed, she will lay a much smaller clutch, and leave them at the bottom of the pond or lake. Eggs will become covered in algae, which helps the developing embryo breathe.",
                            Classification = "Amphibian",
                            CommonName = "Northwestern Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "Dark brown, gray, or black.",
                            Diet = "Small invertebrates, aquatic invertebrates, tadpoles, snails, worms, fairy shrimp.",
                            Diseases = "Could cause sickness in humans if ingested due to their poisonous skin secretions.",
                            Habitat = "Moist habitats such as open grasslands, forests, and woodlands withe nearby freshwater sources.",
                            InvasiveStatus = false,
                            Lifespan = "5 years",
                            PhotoPath = "../wwwroot/uploads/northwesternSalamander.jpg",
                            Predators = "Predatory fish, Rough-skinned newts (often seen eating their eggs), garter snakes, small mammals, birds, fish.",
                            ScientificName = "Ambystoma gracile",
                            Size = "4-10.7 cm"
                        },
                        new
                        {
                            HerpListId = 3,
                            Breeding = "Breeding ranges from January to July, and can be found in groups under natural debris near the edges of the water, especially in April and May. They lay their eggs near the shore lines of ponds and slow moving streams. They will either lay the eggs individually or in bunches in secure places underwater.",
                            Classification = "Amphibian macrodactylum",
                            CommonName = "Long-Toed Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "Dark body with a tan/yellowish/greenish stripe along its back. Their belly is dark with small white speckles. They have one long toe on their back feet (hence the name).",
                            Diet = "Slugs, worms, instect, frog tadpoles, smaller salamander larvae.  For larvae, they eat zooplankton.",
                            Diseases = "Secrets a milky concoction from its tail when  threatened that is noxious, and possibly poisonous.",
                            Habitat = "Moist vegitation near water in forests, prairies or mountain meadows, occasionally in human trafficed areas.",
                            InvasiveStatus = false,
                            Lifespan = "7 years",
                            PhotoPath = "../wwwroot/uploads/Long-toedSalamander.jpg",
                            Predators = "Garter snakes, small mammals, birds, fish",
                            ScientificName = "Ambystoma ",
                            Size = "4-9 cm"
                        },
                        new
                        {
                            HerpListId = 4,
                            Breeding = "They lay around 50-115 eggs in their wet environment, and maybe gaurds them aggressively.",
                            Classification = "Amphibian",
                            CommonName = "Cope's Giant Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "marbled gold brown, costal grooves, latterally compressed tail. Metamorphosed forms are rare. Not much is known of the Cope's Giant Salamander.",
                            Diet = "fish, amphibians, amphibian eggs (including their own).",
                            Habitat = "Clear mountain streams in damp forests.",
                            InvasiveStatus = false,
                            PhotoPath = "../wwwroot/uploads/copesGiantSalamander.jpg",
                            Predators = "Garter Snakes, water shrew.",
                            ScientificName = "Dicamptodon copei",
                            Size = "19.5 cm"
                        },
                        new
                        {
                            HerpListId = 5,
                            Classification = "Amphibian",
                            CommonName = "Coastal Giant Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "light brown or brass-colored skin with dark marbled or reticulated blotched pattern. They are one of the few salamanders capable of vocalizing.",
                            Diet = "Larvae will consume insects, insect larvae, amphipods, ostracods, termatoes, molusks, crayfish, eggs. Adults will eat small mammals, snakes, amphibians, fish, other marine invertebrates.",
                            Habitat = "Small to midsize streams and moist riverside forests with Gravel to small-boulder covered stream beds. They can also be found under forest debris during rainy periods. They can be found in elevations ranging from sea level to 1830 m.",
                            InvasiveStatus = false,
                            PhotoPath = "../wwwroot/uploads/coastalGiantSalamander.jpg",
                            Predators = "Weasels, river otters, water shrews, garter snakes, salmonids, conspecifics.",
                            ScientificName = "Dicamptodon tenebrosus",
                            Size = "34 cm"
                        },
                        new
                        {
                            HerpListId = 6,
                            Classification = "Amphibian",
                            CommonName = "Columbia Torrent Salamander",
                            ConservationStatus = "Near Threatened",
                            Description = "There isn't much known about this species.",
                            Habitat = "Temperate forests, rivers, and freshwater springs. Clear, cold, mountain springs.",
                            InvasiveStatus = false,
                            ScientificName = "Rhyacotriton kezeri",
                            Size = "10 cm"
                        },
                        new
                        {
                            HerpListId = 7,
                            Classification = "Salamander",
                            CommonName = "Southern Torrent Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "",
                            Diet = "",
                            Habitat = "",
                            InvasiveStatus = false,
                            PhotoPath = "../wwwroot/uploads/southernTorrentSalamander.jpg",
                            Predators = "",
                            ScientificName = "Rhyacotriton variegatus",
                            Size = "4-6.2 cm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
