// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OregonHerp.Models;

namespace OregonHerp_Api.Migrations
{
    [DbContext(typeof(OregonHerpContext))]
    [Migration("20200102122315_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("OregonHerp.Models.HerpList", b =>
                {
                    b.Property<int>("HerpListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breeding");

                    b.Property<string>("Classification");

                    b.Property<string>("CommonName");

                    b.Property<string>("ConservationStatus");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Diet");

                    b.Property<string>("Diseases");

                    b.Property<string>("Habitat")
                        .IsRequired();

                    b.Property<bool>("InvasiveStatus");

                    b.Property<string>("Lifespan");

                    b.Property<string>("PhotoPath");

                    b.Property<string>("Predators");

                    b.Property<string>("ScientificName")
                        .IsRequired();

                    b.Property<string>("Size");

                    b.HasKey("HerpListId");

                    b.ToTable("HerpList");

                    b.HasData(
                        new
                        {
                            HerpListId = 1,
                            Breeding = "Tiger salamaders are loyal to where they were born and will travel long distances to return. They have only a 50% chance of breeding more than once in their lifetime and only breed in the later winter and early spring months. This is aproximately when the ground is warmer and the water has thawed. After nudging a willing female, the male will deposite a spermatophore on the lake bottom. After about 48 hours after insemination, the female will lay her eggs in the breeding pool, attaching them to secure places to ensure their safety. It takes Roughly 12-50 days for all of the eggs to hatch, and 3 months to fully mature into adults. Their larvae are entirely aquatic with external gills and a prominent caudal fin, similar to Axolotls. As they grow, they develope limbs shortly after hatching. In certain cases, such as with seasonal pools, they may mature faster, becoming small morph adults. In other cases where the weather is warmer and ancestral pools, they may not metamorphose until they are adult size. They also have been known to never metamorphose and stay in their larva stage their entire lives and reach sexual maturity while in their larva form.",
                            Classification = "Amphibian",
                            CommonName = "Tiger Salamander",
                            ConservationStatus = "Least Concern",
                            Description = "They are easily identified by their brown or black bodies with either brownish-yellow or greenish yellow spots on their heads, bodies, and tails.",
                            Diet = "Insects, earthworms, grubs, small snails, slugs, minnows, other amphibians (in rare cases, other tiger salamanders), crustacians (while in their larva form).",
                            Diseases = "Although immune, tiger salamaders transmit amphibian chytrid fungus which causes Chytridiomycosis which affects amphibians worldwide. They also carry ranaviruses which infects reptiles, amphibians, and fish, and has been linked to high mortality in tiger salamander larvae when there's reoccuring ranavirus infections.",
                            Habitat = "Wetlands, rivers and streams. They are mostly terrestrial, only returning to the water to breed.",
                            InvasiveStatus = false,
                            Lifespan = "12-15 years",
                            PhotoPath = "../wwwroot/uploads/tigerSalamander.jpg",
                            Predators = "Racoons, Coatis, river turtles.",
                            ScientificName = "Ambystoma tigrinum",
                            Size = "15-35 cm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
