// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter_Api.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("AnimalShelter.Models.ShelterList", b =>
                {
                    b.Property<int>("ShelterListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("KennelNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PhotoPath")
                        .IsRequired();

                    b.HasKey("ShelterListId");

                    b.ToTable("ShelterList");

                    b.HasData(
                        new
                        {
                            ShelterListId = 1,
                            Age = "Young",
                            AnimalType = "Alpaca",
                            Breed = "Suri",
                            Description = "Carla is sassy and loves big Open spaces. She is the leader of the al-Pack-as.",
                            Gender = "Female",
                            KennelNumber = "7E",
                            Name = "Carla",
                            PhotoPath = "wwwroot/uploads/Carla.jpg"
                        },
                        new
                        {
                            ShelterListId = 2,
                            Age = "Teen",
                            AnimalType = "Caiman",
                            Breed = "Cuvier's dwarf",
                            Description = "He may be small, but Ruddy is feisty. Watch your fingers!",
                            Gender = "Male",
                            KennelNumber = "1R",
                            Name = "Ruddy",
                            PhotoPath = "wwwroot/uploads/Ruddy.jpg"
                        },
                        new
                        {
                            ShelterListId = 3,
                            Age = "Young",
                            AnimalType = "Frog",
                            Breed = "Tomato",
                            Description = "He's a  frog. He does froggy things. He loves the hand taxi. Will do a heckin' monch before trusting hand taxi.",
                            Gender = "Male",
                            KennelNumber = "5A",
                            Name = "Sticky",
                            PhotoPath = "wwwroot/uploads/Sticky.jpg"
                        },
                        new
                        {
                            ShelterListId = 4,
                            Age = "Young",
                            AnimalType = "Dog",
                            Breed = "Chinese Crested",
                            Description = "Toad is a fashionista. If she isn't wearing a cute outfit, she shakes uncontrollably from her naked rage.",
                            Gender = "Female",
                            KennelNumber = "3D",
                            Name = "Toad",
                            PhotoPath = "wwwroot/uploads/King.jpg"
                        },
                        new
                        {
                            ShelterListId = 5,
                            Age = "Teen",
                            AnimalType = "Cat",
                            Breed = "Ragdoll",
                            Description = "Raggedy Anne is a very relaxed. Her favorite pastime is sleeping and getting attention.",
                            Gender = "Female",
                            KennelNumber = "3B",
                            Name = "Raggedy Anne",
                            PhotoPath = "wwwroot/uploads/Anne.jpg"
                        },
                        new
                        {
                            ShelterListId = 6,
                            Age = "Young",
                            AnimalType = "Bird",
                            Breed = "Red Factor Canary",
                            Description = "Loves heavy metal music. You must give him the seed or he will fight you.",
                            Gender = "Male",
                            KennelNumber = "1B",
                            Name = "Blood",
                            PhotoPath = "wwwroot/uploads/Blood.jpg"
                        },
                        new
                        {
                            ShelterListId = 7,
                            Age = "Adult",
                            AnimalType = "Monkey",
                            Breed = "Emperor Tamerin",
                            Description = "King Arthor believes He is king of all animals. Will steal your heart and your Acai fruit.",
                            Gender = "Male",
                            KennelNumber = "7G",
                            Name = "King Arthor",
                            PhotoPath = "wwwroot/uploads/Toad.jpg"
                        },
                        new
                        {
                            ShelterListId = 8,
                            Age = "Teen",
                            AnimalType = "Crab",
                            Breed = "Chesapeake blue Crab",
                            Description = "Always Angry.",
                            Gender = "Male",
                            KennelNumber = "3F",
                            Name = "Crab",
                            PhotoPath = "wwwroot/uploads/Crab.jpg"
                        },
                        new
                        {
                            ShelterListId = 9,
                            Age = "Young",
                            AnimalType = "Fish",
                            Breed = "Paedocypris progenetica",
                            Description = "So tiny, you can barely see her. Blubbles Just likes doing her own thing.",
                            Gender = "Female",
                            KennelNumber = "2F",
                            Name = "Blubbles",
                            PhotoPath = "wwwroot/uploads/Blub.jpg"
                        },
                        new
                        {
                            ShelterListId = 10,
                            Age = "Adult",
                            AnimalType = "Cougar",
                            Breed = "Cougar",
                            Description = "We aren't sure how we got Tom, but she seems friendly.",
                            Gender = "Female",
                            KennelNumber = "7V",
                            Name = "Tom",
                            PhotoPath = "wwwroot/uploads/Tom.jpg"
                        },
                        new
                        {
                            ShelterListId = 11,
                            Age = "Adult",
                            AnimalType = "Elephant",
                            Breed = "Borneo Elephant",
                            Description = "Borneo is smaller than he should be. He acts like a puppy dog, even loves playing catch.",
                            Gender = "Male",
                            KennelNumber = "5D",
                            Name = "Stompers",
                            PhotoPath = "wwwroot/uploads/Stompers.jpg"
                        },
                        new
                        {
                            ShelterListId = 12,
                            Age = "???",
                            AnimalType = "Dragon",
                            Breed = "Luck Dragon",
                            Description = "You mean... We have THE Falcore?! Falcore from the Never Ending Story?!",
                            Gender = "Male",
                            KennelNumber = "7H",
                            Name = "Falcore",
                            PhotoPath = "wwwroot/uploads/Flacore.jpg"
                        },
                        new
                        {
                            ShelterListId = 13,
                            Age = "Ancient",
                            AnimalType = "Rock",
                            Breed = "Rock",
                            Description = "Um... it's... a rock.",
                            Gender = "None",
                            KennelNumber = "1A",
                            Name = "Rockita",
                            PhotoPath = "wwwroot/uploads/Rockita.jpg"
                        },
                        new
                        {
                            ShelterListId = 14,
                            Age = "Young",
                            AnimalType = "Plant",
                            Breed = "Lithop",
                            Description = "The cutest little plant on planet earth! Just look at all that cuteness!",
                            Gender = "None",
                            KennelNumber = "2A",
                            Name = "Cutie",
                            PhotoPath = "wwwroot/uploads/Cutie.jpg"
                        },
                        new
                        {
                            ShelterListId = 15,
                            Age = "Elder",
                            AnimalType = "Spider",
                            Breed = "Bold Jumper",
                            Description = "Jumpy's eyes are very mesmerizing! We can't look away.",
                            Gender = "Female",
                            KennelNumber = "1C",
                            Name = "Jumpy",
                            PhotoPath = "wwwroot/uploads/Jumpy.jpg"
                        },
                        new
                        {
                            ShelterListId = 16,
                            Age = "Adult",
                            AnimalType = "Human",
                            Breed = "Nerd",
                            Description = "Hey! Guys, This ain't funny! Take this down!",
                            Gender = "Male",
                            KennelNumber = "Office",
                            Name = "Brad Person",
                            PhotoPath = "wwwroot/uploads/Brad_Person.jpg"
                        },
                        new
                        {
                            ShelterListId = 17,
                            Age = "Young",
                            AnimalType = "Dog",
                            Breed = "Australian Shepherd",
                            Description = "Misty is Very active and very loyal. Her previous owner gaver her up because Misty didn't want to hurt the sheep.",
                            Gender = "Female",
                            KennelNumber = "4D",
                            Name = "Mist",
                            PhotoPath = "wwwroot/uploads/Misty.jpg"
                        },
                        new
                        {
                            ShelterListId = 87,
                            Age = "young",
                            AnimalType = "Cat",
                            Breed = "Japanese Bontail",
                            Description = "Xander is very vocal an loves to play. He still has his kitten energy and will need lot of play.",
                            Gender = "Male",
                            KennelNumber = "3C",
                            Name = "Xander",
                            PhotoPath = "wwwroot/uploads/Xander.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
